apiVersion: v1
clusters:
- cluster:
    server: https://napi.arvancloud.ir/caas/v2/regions/ir-central1
  name: ir-central1
contexts:
- context:
    cluster: ir-central1
    namespace: analysis-data2
    user: dcb95f96-8a40-584e-b440-44243b322f95
  name: ir-central1
current-context: ir-central1
kind: Config
users:
- name: dcb95f96-8a40-584e-b440-44243b322f95
  user:
    token: fffd7f66-fdd8-5646-94af-18c459b074bb
