apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 200Mi
              memory: 250Mi
            requests:
              cpu: 100m
              ephemeral-storage: 100Mi
              memory: 100Mi

          ports:
            - containerPort: 5432
          env:  
          - name: POSTGRES_USER  
            value: "postgres"  
          - name: POSTGRES_PASSWORD  
            value: "1234"
          - name: POSTGRES_DB
            value: "mohaymen"
          - name: HOST
            value: "postgres"
          - name: PORT
            value: "5432"
            #  envFrom:
            # - configMapRef:
            # name: db-secrets-net
          volumeMounts:
          - mountPath: /var/lib/postgres/data
            name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-pvc
