apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: angular-nginx  
  labels:  
    app: angular  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: angular  
  template:  
    metadata:  
      labels:  
        app: angular  
    spec:  
      containers:  
      - name: nginx  
        image: angular_image_tmp2 # angular_image_tmp:latest  # Update with your image 
        imagePullPolicy: IfNotPresent
        ports:  
        - containerPort: 80  
