apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: webimage
          imagePullPolicy: IfNotPresent
            #env:
            #- name: ConnectionStrings__DefaultConnection
            #  value: "Host=postgres;Database=mohaymen;Username=postgres;Password=1234"

          #ConnectionStrings__DefaultConnection: Host=postgres;Database=mohaymen;Username=postgres;Password=1234;
          #env:
          #  - name: DBConnection__Host
          #    value: postgres
          #  - name: DBConnection__Port
          #    value: "5432"
          #  - name: DBConnection__User
          #    value: postgres
          #  - name: DBConnection__Password
          #    value: "1234"
          #  - name: DBConnection__Database
          #    value: mohaymen
          #  - name: ASPNETCORE_URLS
          #    value: "http://*:80"
          env:  
          - name: ConnectionStrings__DefaultConnection  
            valueFrom:  
              configMapKeyRef:  
                name: db-secrets-net
                key: POSTGRES_CONNECTION_STRING 
          ports:
          - containerPort: 80
