apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
        
  template:
    metadata:
      labels:
        app: web

    spec:
      initContainers:
        - name: init-container
          image: yaghooli/migrateimage:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              configMapKeyRef:
                name: db-secrets-net
                key: POSTGRES_CONNECTION_STRING

                  #          command: ['sh', '-c']           # Overriding the command  
                  #args:  
                  # - |  
                  # DATABASE_DOMAIN=$ConnectionStrings__DefaultConnection
                  #  echo "Database domain is $DATABASE_DOMAIN"  

      containers:
        - name: web
          image: tmp_dotnet3 #yaghooli/dotnetdev:latest #webimage4 yaghooli/dotnetdev:latest
          imagePullPolicy: IfNotPresent
            #command: ["dotnet", "ef", "--project", "AnalysisData/AnalysisData/AnalysisData.csproj", "database", "update"]  

          env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              configMapKeyRef:
                name: db-secrets-net
                key: POSTGRES_CONNECTION_STRING

          ports:
          - containerPort: 80
