postgres:  
  db: "mohaymen"  
  user: "postgres"  
  password: "1234"  
  host: "postgres"  
  port: "5432"  
  image:  
    repository: postgres  
    tag: "16"  
  resources:  
    limits:  
      cpu: "1000m"  
      memory: "2000Mi"
      ephemeral-storage: "1000Mi"

    requests:  
      cpu: "1000m"  
      memory: "2000Mi" 
      ephemeral-storage: "1000Mi"
 
  persistence:  
    enabled: true  
    size: "3Gi"  

angular:  
  image:  
    repository: yaghooli/frontangular:v0.15.3
    #registry.abriment.com/yaghooli/angular_image_tmp2  

  service:  
    type: ClusterIP

  resources:
    limits:
      cpu: "2000m"
      memory: "4000Mi"
      ephemeral-storage: "1000Mi"

    requests:
      cpu: "1500m"
      memory: "3000Mi"
      ephemeral-storage: "1000Mi"

init:
  image: 
    repository: yaghooli/migrateimage:v0.13.5

web:  
  image:  
    repository: yaghooli/dotnetdev:v0.13.5

  service:  
    type: ClusterIP  

  resources:
    limits:
      cpu: "1000m"
      memory: "2000Mi"
      ephemeralstorage: "1000Mi"

    requests:
      cpu: "1000m"
      memory: "2000Mi"
      ephemeralstorage: "1000Mi"

storage:  
  size: 3Gi 

      #imagePullSecrets:  
  #  - name: my-registry-secret  

    #ingress:  
  # enabled: true  
    #  host: myapp.local
