postgres:  
  db: "stardataaa"  
  user: "yaghooli"  
  password: "Aliyaghini110110@"  
  host: "stardataaa.83ddaaf9a69e4d4d86caf49e649f8464-dbaas-postgresql-a361fcd1ad5cf.svc.cluster.local:5432"  
  port: "5432"  
  image:  
    repository: postgres  
    tag: "16"  
  resources:  
    limits:  
      cpu: "1000m"  
      memory: "2000Mi"
      ephemeral-storage: "1000Mi"

    requests:  
      cpu: "1000m"  
      memory: "2000Mi" 
      ephemeral-storage: "1000Mi"
 
  persistence:  
    enabled: true  
    size: "3Gi"  

angular:  
  image:  
    repository: yaghooli/frontangular:v0.24.2
    #registry.abriment.com/yaghooli/angular_image_tmp2  

  service:  
    type: ClusterIP

  resources:
    limits:
      cpu: "1000m"
      memory: "1000Mi"
      ephemeral-storage: "1000Mi"

    requests:
      cpu: "1000m"
      memory: "1000Mi"
      ephemeral-storage: "1000Mi"

init:
  image: 
    repository: yaghooli/migrateimage:v0.15.39

web:  
  image:  
    repository: yaghooli/dotnetdev:v0.15.39

  service:  
    type: ClusterIP  

  resources:
    limits:
      cpu: "1000m"
      memory: "2000Mi"
      ephemeralstorage: "1000Mi"

    requests:
      cpu: "1000m"
      memory: "2000Mi"
      ephemeralstorage: "1000Mi"

storage:  
  size: 3Gi 

      #imagePullSecrets:  
  #  - name: my-registry-secret  

    #ingress:  
  # enabled: true  
    #  host: myapp.local
