apiVersion: v1  
kind: Service  
metadata:  
  name: angular-nginx-service  
spec:  
  type: {{ .Values.angular.service.type }}   
  ports:  
    - port: 80  
      targetPort: 80  
  selector:  
    app: angular
